# Generated by Django 4.0 on 2025-03-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('lang', models.TextField()),
                ('dir', models.TextField()),
                ('page_name', models.TextField()),
                ('slug', models.TextField()),
                ('meta_title', models.TextField()),
                ('meta_description', models.TextField()),
                ('header', models.TextField()),
                ('heading', models.TextField()),
                ('tag_line', models.TextField()),
                ('message_one', models.TextField()),
                ('message_two', models.TextField()),
                ('banner_ad_one', models.TextField()),
                ('banner_ad_two', models.TextField()),
                ('placeholder', models.TextField()),
                ('form_button_text', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=250, unique=True)),
                ('redirect_url', models.TextField()),
                ('http_status_code', models.PositiveIntegerField(default=301)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe_url', models.TextField()),
                ('cobalt_api_url', models.TextField()),
                ('current_use', models.TextField()),
                ('direct_ad', models.TextField()),
                ('social_link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.TextField()),
                ('slug', models.TextField()),
                ('meta_title', models.TextField()),
                ('meta_description', models.TextField()),
                ('header', models.TextField()),
                ('content', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_pages', to='api.languages')),
            ],
        ),
        migrations.CreateModel(
            name='DirectRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='api.languages')),
            ],
        ),
    ]
