# Generated by Django 4.0 on 2025-03-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_light', models.TextField(default='#FFFFFF')),
                ('bg_dark', models.TextField(default='#293033')),
                ('text_dark', models.TextField(default='black')),
                ('text_light', models.TextField(default='white')),
                ('border_light', models.TextField(default='#cccccc')),
                ('border_dark', models.TextField(default='#444')),
                ('toggle_bg', models.TextField(default='#111')),
                ('moon_color', models.TextField(default='#f1c40f')),
                ('sun_color', models.TextField(default='#f39c12')),
                ('dropdown_bg_light', models.TextField(default='#f9f9f9')),
                ('dropdown_bg_dark', models.TextField(default='#444')),
                ('dropdown_hover_light', models.TextField(default='#e0e0e0')),
                ('dropdown_hover_dark', models.TextField(default='#666')),
                ('message_bg_light', models.TextField(default='#EDF7ED')),
                ('message_bg_dark', models.TextField(default='#222')),
                ('message_icon', models.TextField(default='#2e7d32')),
                ('input_border', models.TextField(default='#666666ad')),
                ('search_bg_light', models.TextField(default='#f8f8f8')),
                ('search_bg_dark', models.TextField(default='#222')),
                ('search_button_bg', models.TextField(default='#000000')),
                ('download_now_button_bg', models.TextField(default='#000000')),
                ('convert_another_button_bg', models.TextField(default='#000000')),
                ('follow_us_button_bg', models.TextField(default='#000000')),
                ('mp3_button_bg', models.TextField(default='#000000')),
                ('mp4_button_bg', models.TextField(default='#000000')),
            ],
        ),
    ]
